name: sfu
description: "Mobile application for SFU"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  mobile_scanner: ^7.1.4
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0
  dio: ^5.9.1
  intl: ^0.20.2
  flutter_secure_storage: ^10.0.0
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0
  image_picker: ^1.2.2
  web_socket_channel: ^3.0.2
  slang: ^4.4.0
  slang_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.15.0
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  flutter_launcher_icons: ^0.13.1
  slang_build_runner: ^4.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/logo_app_bar.svg
    - assets/images/QR.svg
    - assets/images/event-schedule.svg
    - assets/images/list.svg
    - assets/images/recordBook.svg
    - lib/src/core/mock/announcements.json
    - lib/src/core/mock/events.json
    - lib/src/core/mock/staff.json
    - lib/src/core/mock/students.json
    - lib/src/core/mock/theses.json
    - lib/src/core/mock/timetable.json
    - lib/src/core/mock/chats.json
    - lib/src/core/mock/messages.json
    - lib/src/core/mock/attendance_records.json
    - .env